import { 
  Folder, 
  Heart, 
  Star, 
  Home, 
  Work,
  Book,
  Camera,
  Music,
  Video,
  Image,
  Code,
  Settings,
  User,
  Users,
  Calendar,
  Clock,
  Bell,
  Mail,
  Phone,
  Map,
  ShoppingCart,
  CreditCard,
  Briefcase,
  GraduationCap,
  Gamepad2,
  Palette,
  Coffee,
  Car,
  Plane,
  Bike,
  TreePine,
  Flower,
  Sun,
  Moon,
  Cloud,
  Zap,
  Shield,
  Key,
  Lock,
  Unlock,
  Gift,
  Trophy,
  Target,
  Rocket,
  Lightbulb,
  Bookmark,
  FileText,
  FolderOpen,
  Archive,
  Database,
  Download,
  Upload,
  Share,
  Link,
  Globe,
  Wifi,
  Smartphone,
  Laptop,
  Monitor,
  Headphones,
  Mic,
  Speaker,
  Volume2,
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Search,
  Filter,
  Sort,
  Grid,
  List,
  MoreHorizontal,
  Plus,
  Minus,
  X,
  Check,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Maximize,
  Minimize,
  Eye,
  EyeOff,
  Edit,
  Trash2,
  Copy,
  Scissors,
  Clipboard,
  Save,
  Print,
  QrCode,
  Barcode,
  Calculator,
  Ruler,
  Compass,
  MapPin,
  Navigation,
  Anchor,
  Flag,
  Tag,
  Hash,
  AtSign,
  Percent,
  DollarSign,
  Euro,
  Pound,
  Yen,
  Bitcoin,
  TrendingUp,
  TrendingDown,
  Activity,
  BarChart3,
  PieChart,
  LineChart,
  ScatterChart,
  Layers,
  Package,
  Box,
  Cube,
  Pyramid,
  Shapes,
  Circle,
  Square as SquareIcon,
  Triangle,
  Hexagon,
  Pentagon,
  Octagon,
  Diamond,
  Sparkles,
  Flame,
  Snowflake,
  Droplets,
  Leaf,
  Flower2,
  Bug,
  Fish,
  Bird,
  Rabbit,
  Cat,
  Dog,
  Turtle,
  Squirrel,
  Elephant,
  Tiger,
  Lion,
  Bear,
  Bone,
  Apple,
  Banana,
  Cherry,
  Grape,
  Orange,
  Strawberry,
  Watermelon,
  Carrot,
  Broccoli,
  Corn,
  Bread,
  Cake,
  Cookie,
  IceCream,
  Pizza,
  Sandwich,
  Soup,
  Salad,
  Utensils,
  ChefHat,
  Wine,
  Beer,
  Cocktail,
  Milk,
  Juice,
  Soda,
  Pill,
  Stethoscope,
  Thermometer,
  Bandage,
  Scissors as ScissorsIcon,
  Syringe,
  Glasses,
  Sunglasses,
  Watch,
  Crown,
  Gem,
  Ring,
  Necklace,
  Shirt,
  Jacket,
  Dress,
  Shoe,
  Hat,
  Umbrella,
  Backpack,
  Luggage,
  Tent,
  Compass as CompassIcon,
  Map as MapIcon,
  Ticket,
  Hotel,
  Building,
  Building2,
  Home as HomeIcon,
  School,
  Hospital,
  Store,
  Factory,
  Warehouse,
  Church,
  Mosque,
  Synagogue,
  Stadium,
  Theatre,
  Museum,
  Library,
  Bank,
  Post,
  Police,
  Fire,
  Ambulance,
  Truck,
  Bus,
  Train,
  Subway,
  Taxi,
  Ship,
  Boat,
  Helicopter,
  Rocket as RocketIcon,
  Satellite,
  Ufo,
  Alien,
  Robot,
  Skull,
  Ghost,
  Circle as PumpkinIcon,
  Tree as ChristmasTreeIcon,
  Snowflake as SnowmanIcon,
  Sparkles as FireworksIcon,
  Circle as BalloonIcon,
  Sparkles as PartyPopperIcon,
  Sparkles as ConfettiIcon,
  Square as Dice1Icon,
  Square as Dice2Icon,
  Square as Dice3Icon,
  Square as Dice4Icon,
  Square as Dice5Icon,
  Square as Dice6Icon,
  Diamond as SpadeIcon,
  Circle as ClubIcon,
  Heart as HeartIcon,
  Diamond as DiamondIcon,
  Square as ChessIcon,
  Grid3x3 as PuzzleIcon,
  Target as CrosshairIcon,
  Zap as ZapIcon,
  Flame as FlameIcon,
  Wind,
  Wind as TornadoIcon,
  Circle as RainbowIcon,
  Sun as SunriseIcon,
  Sun as SunsetIcon,
  Cloud as CloudRainIcon,
  Cloud as CloudSnowIcon,
  Cloud as CloudLightningIcon,
  Thermometer as ThermometerIcon
} from 'lucide-react';

export interface IconInfo {
  name: string;
  icon: typeof Folder;
  category: string;
  keywords: string[];
}

// 아이콘 카테고리 정의
export const iconCategories = {
  default: 'Default',
  work: 'Work',
  home: 'Home',
  entertainment: 'Entertainment',
  education: 'Education',
  health: 'Health',
  travel: 'Travel',
  food: 'Food',
  nature: 'Nature',
  animals: 'Animals',
  technology: 'Technology',
  fashion: 'Fashion',
  sports: 'Sports',
  finance: 'Finance',
  weather: 'Weather',
  buildings: 'Buildings',
  transport: 'Transport',
  symbols: 'Symbols',
  shapes: 'Shapes',
  holidays: 'Holidays',
  games: 'Games'
} as const;

export type IconCategory = keyof typeof iconCategories;

// 아이콘 데이터 정의
export const iconData: IconInfo[] = [
  // Default 카테고리
  { name: 'folder', icon: Folder, category: 'default', keywords: ['folder', 'directory', 'file'] },
  { name: 'folder-open', icon: FolderOpen, category: 'default', keywords: ['folder', 'open', 'directory'] },
  { name: 'bookmark', icon: Bookmark, category: 'default', keywords: ['bookmark', 'save', 'favorite'] },
  { name: 'star', icon: Star, category: 'default', keywords: ['star', 'favorite', 'important'] },
  { name: 'heart', icon: Heart, category: 'default', keywords: ['heart', 'love', 'like'] },
  
  // Work 카테고리
  { name: 'briefcase', icon: Briefcase, category: 'work', keywords: ['work', 'job', 'business'] },
  { name: 'code', icon: Code, category: 'work', keywords: ['code', 'programming', 'development'] },
  { name: 'settings', icon: Settings, category: 'work', keywords: ['settings', 'configuration', 'tools'] },
  { name: 'database', icon: Database, category: 'work', keywords: ['database', 'storage', 'data'] },
  { name: 'monitor', icon: Monitor, category: 'work', keywords: ['monitor', 'computer', 'screen'] },
  { name: 'laptop', icon: Laptop, category: 'work', keywords: ['laptop', 'computer', 'work'] },
  { name: 'smartphone', icon: Smartphone, category: 'work', keywords: ['phone', 'mobile', 'smartphone'] },
  
  // Home 카테고리
  { name: 'home', icon: Home, category: 'home', keywords: ['home', 'house', 'family'] },
  { name: 'user', icon: User, category: 'home', keywords: ['user', 'person', 'profile'] },
  { name: 'users', icon: Users, category: 'home', keywords: ['users', 'people', 'family'] },
  { name: 'calendar', icon: Calendar, category: 'home', keywords: ['calendar', 'date', 'schedule'] },
  { name: 'clock', icon: Clock, category: 'home', keywords: ['time', 'clock', 'schedule'] },
  { name: 'bell', icon: Bell, category: 'home', keywords: ['notification', 'alert', 'reminder'] },
  { name: 'mail', icon: Mail, category: 'home', keywords: ['email', 'message', 'communication'] },
  { name: 'phone', icon: Phone, category: 'home', keywords: ['phone', 'call', 'contact'] },
  
  // Entertainment 카테고리
  { name: 'music', icon: Music, category: 'entertainment', keywords: ['music', 'song', 'audio'] },
  { name: 'video', icon: Video, category: 'entertainment', keywords: ['video', 'movie', 'film'] },
  { name: 'camera', icon: Camera, category: 'entertainment', keywords: ['camera', 'photo', 'picture'] },
  { name: 'image', icon: Image, category: 'entertainment', keywords: ['image', 'photo', 'picture'] },
  { name: 'gamepad', icon: Gamepad2, category: 'entertainment', keywords: ['game', 'gaming', 'play'] },
  { name: 'palette', icon: Palette, category: 'entertainment', keywords: ['art', 'color', 'design'] },
  { name: 'headphones', icon: Headphones, category: 'entertainment', keywords: ['headphones', 'music', 'audio'] },
  { name: 'mic', icon: Mic, category: 'entertainment', keywords: ['microphone', 'voice', 'recording'] },
  { name: 'speaker', icon: Speaker, category: 'entertainment', keywords: ['speaker', 'audio', 'sound'] },
  
  // Education 카테고리
  { name: 'book', icon: Book, category: 'education', keywords: ['book', 'read', 'study'] },
  { name: 'graduation-cap', icon: GraduationCap, category: 'education', keywords: ['education', 'school', 'university'] },
  { name: 'lightbulb', icon: Lightbulb, category: 'education', keywords: ['idea', 'innovation', 'creativity'] },
  { name: 'file-text', icon: FileText, category: 'education', keywords: ['document', 'text', 'file'] },
  { name: 'calculator', icon: Calculator, category: 'education', keywords: ['calculator', 'math', 'numbers'] },
  { name: 'ruler', icon: Ruler, category: 'education', keywords: ['ruler', 'measure', 'geometry'] },
  
  // Health 카테고리
  { name: 'stethoscope', icon: Stethoscope, category: 'health', keywords: ['doctor', 'medical', 'health'] },
  { name: 'pill', icon: Pill, category: 'health', keywords: ['medicine', 'pill', 'health'] },
  { name: 'thermometer', icon: Thermometer, category: 'health', keywords: ['temperature', 'fever', 'health'] },
  { name: 'bandage', icon: Bandage, category: 'health', keywords: ['bandage', 'first-aid', 'medical'] },
  { name: 'activity', icon: Activity, category: 'health', keywords: ['fitness', 'exercise', 'health'] },
  
  // Travel 카테고리
  { name: 'plane', icon: Plane, category: 'travel', keywords: ['airplane', 'flight', 'travel'] },
  { name: 'car', icon: Car, category: 'travel', keywords: ['car', 'vehicle', 'transport'] },
  { name: 'bike', icon: Bike, category: 'travel', keywords: ['bicycle', 'bike', 'cycling'] },
  { name: 'map', icon: Map, category: 'travel', keywords: ['map', 'location', 'navigation'] },
  { name: 'map-pin', icon: MapPin, category: 'travel', keywords: ['location', 'pin', 'place'] },
  { name: 'compass', icon: Compass, category: 'travel', keywords: ['compass', 'direction', 'navigation'] },
  { name: 'luggage', icon: Luggage, category: 'travel', keywords: ['luggage', 'suitcase', 'travel'] },
  { name: 'tent', icon: Tent, category: 'travel', keywords: ['tent', 'camping', 'outdoor'] },
  
  // Food 카테고리
  { name: 'coffee', icon: Coffee, category: 'food', keywords: ['coffee', 'drink', 'beverage'] },
  { name: 'apple', icon: Apple, category: 'food', keywords: ['apple', 'fruit', 'healthy'] },
  { name: 'pizza', icon: Pizza, category: 'food', keywords: ['pizza', 'food', 'restaurant'] },
  { name: 'cake', icon: Cake, category: 'food', keywords: ['cake', 'dessert', 'sweet'] },
  { name: 'utensils', icon: Utensils, category: 'food', keywords: ['utensils', 'eat', 'restaurant'] },
  { name: 'chef-hat', icon: ChefHat, category: 'food', keywords: ['chef', 'cooking', 'restaurant'] },
  { name: 'wine', icon: Wine, category: 'food', keywords: ['wine', 'drink', 'alcohol'] },
  
  // Nature 카테고리
  { name: 'tree-pine', icon: TreePine, category: 'nature', keywords: ['tree', 'nature', 'forest'] },
  { name: 'flower', icon: Flower, category: 'nature', keywords: ['flower', 'nature', 'garden'] },
  { name: 'leaf', icon: Leaf, category: 'nature', keywords: ['leaf', 'nature', 'plant'] },
  { name: 'sun', icon: Sun, category: 'nature', keywords: ['sun', 'sunny', 'weather'] },
  { name: 'moon', icon: Moon, category: 'nature', keywords: ['moon', 'night', 'sky'] },
  { name: 'cloud', icon: Cloud, category: 'nature', keywords: ['cloud', 'weather', 'sky'] },
  { name: 'droplets', icon: Droplets, category: 'nature', keywords: ['water', 'rain', 'drops'] },
  { name: 'snowflake', icon: Snowflake, category: 'nature', keywords: ['snow', 'winter', 'cold'] },
  
  // Animals 카테고리
  { name: 'cat', icon: Cat, category: 'animals', keywords: ['cat', 'pet', 'animal'] },
  { name: 'dog', icon: Dog, category: 'animals', keywords: ['dog', 'pet', 'animal'] },
  { name: 'fish', icon: Fish, category: 'animals', keywords: ['fish', 'sea', 'animal'] },
  { name: 'bird', icon: Bird, category: 'animals', keywords: ['bird', 'fly', 'animal'] },
  { name: 'rabbit', icon: Rabbit, category: 'animals', keywords: ['rabbit', 'bunny', 'animal'] },
  { name: 'turtle', icon: Turtle, category: 'animals', keywords: ['turtle', 'slow', 'animal'] },
  { name: 'bug', icon: Bug, category: 'animals', keywords: ['bug', 'insect', 'animal'] },
  { name: 'paw', icon: Dog, category: 'animals', keywords: ['paw', 'pet', 'animal', 'dog'] },
  
  // Technology 카테고리
  { name: 'wifi', icon: Wifi, category: 'technology', keywords: ['wifi', 'internet', 'network'] },
  { name: 'globe', icon: Globe, category: 'technology', keywords: ['internet', 'global', 'web'] },
  { name: 'link', icon: Link, category: 'technology', keywords: ['link', 'url', 'connection'] },
  { name: 'share', icon: Share, category: 'technology', keywords: ['share', 'social', 'network'] },
  { name: 'download', icon: Download, category: 'technology', keywords: ['download', 'save', 'file'] },
  { name: 'upload', icon: Upload, category: 'technology', keywords: ['upload', 'share', 'file'] },
  { name: 'qr-code', icon: QrCode, category: 'technology', keywords: ['qr', 'code', 'scan'] },
  { name: 'zap', icon: Zap, category: 'technology', keywords: ['energy', 'power', 'electric'] },
  
  // Finance 카테고리
  { name: 'dollar-sign', icon: DollarSign, category: 'finance', keywords: ['money', 'dollar', 'finance'] },
  { name: 'credit-card', icon: CreditCard, category: 'finance', keywords: ['credit', 'card', 'payment'] },
  { name: 'shopping-cart', icon: ShoppingCart, category: 'finance', keywords: ['shopping', 'cart', 'buy'] },
  { name: 'trending-up', icon: TrendingUp, category: 'finance', keywords: ['growth', 'profit', 'success'] },
  { name: 'trending-down', icon: TrendingDown, category: 'finance', keywords: ['loss', 'decline', 'down'] },
  { name: 'pie-chart', icon: PieChart, category: 'finance', keywords: ['chart', 'statistics', 'data'] },
  { name: 'bar-chart', icon: BarChart3, category: 'finance', keywords: ['chart', 'statistics', 'data'] },
  
  // Symbols 카테고리
  { name: 'shield', icon: Shield, category: 'symbols', keywords: ['security', 'protection', 'safe'] },
  { name: 'key', icon: Key, category: 'symbols', keywords: ['key', 'password', 'access'] },
  { name: 'lock', icon: Lock, category: 'symbols', keywords: ['lock', 'secure', 'private'] },
  { name: 'unlock', icon: Unlock, category: 'symbols', keywords: ['unlock', 'open', 'access'] },
  { name: 'gift', icon: Gift, category: 'symbols', keywords: ['gift', 'present', 'surprise'] },
  { name: 'trophy', icon: Trophy, category: 'symbols', keywords: ['trophy', 'award', 'winner'] },
  { name: 'target', icon: Target, category: 'symbols', keywords: ['target', 'goal', 'aim'] },
  { name: 'rocket', icon: Rocket, category: 'symbols', keywords: ['rocket', 'launch', 'space'] },
  { name: 'flag', icon: Flag, category: 'symbols', keywords: ['flag', 'country', 'mark'] },
  { name: 'tag', icon: Tag, category: 'symbols', keywords: ['tag', 'label', 'category'] },
  { name: 'crown', icon: Crown, category: 'symbols', keywords: ['crown', 'royal', 'king'] },
  { name: 'gem', icon: Gem, category: 'symbols', keywords: ['gem', 'diamond', 'precious'] },
  
  // Shapes 카테고리
  { name: 'circle', icon: Circle, category: 'shapes', keywords: ['circle', 'round', 'shape'] },
  { name: 'square', icon: SquareIcon, category: 'shapes', keywords: ['square', 'box', 'shape'] },
  { name: 'triangle', icon: Triangle, category: 'shapes', keywords: ['triangle', 'shape', 'geometry'] },
  { name: 'hexagon', icon: Hexagon, category: 'shapes', keywords: ['hexagon', 'shape', 'geometry'] },
  { name: 'diamond', icon: Diamond, category: 'shapes', keywords: ['diamond', 'shape', 'gem'] },
  { name: 'sparkles', icon: Sparkles, category: 'shapes', keywords: ['sparkles', 'magic', 'shine'] },
];

// 카테고리별 아이콘 필터링
export const getIconsByCategory = (category: IconCategory): IconInfo[] => {
  return iconData.filter(icon => icon.category === category);
};

// 키워드로 아이콘 검색
export const searchIcons = (query: string): IconInfo[] => {
  const lowerQuery = query.toLowerCase();
  return iconData.filter(icon => 
    icon.name.toLowerCase().includes(lowerQuery) ||
    icon.keywords.some(keyword => keyword.toLowerCase().includes(lowerQuery))
  );
};

// 아이콘 이름으로 아이콘 정보 가져오기
export const getIconByName = (name: string): IconInfo | undefined => {
  return iconData.find(icon => icon.name === name);
};

// 모든 카테고리 목록 가져오기
export const getAllCategories = (): { key: IconCategory; label: string }[] => {
  return Object.entries(iconCategories).map(([key, label]) => ({
    key: key as IconCategory,
    label
  }));
};

// 기본 색상 팔레트
export const defaultColors = [
  '#3B82F6', // blue-500
  '#EF4444', // red-500
  '#10B981', // emerald-500
  '#F59E0B', // amber-500
  '#8B5CF6', // violet-500
  '#EC4899', // pink-500
  '#06B6D4', // cyan-500
  '#84CC16', // lime-500
  '#F97316', // orange-500
  '#6366F1', // indigo-500
  '#14B8A6', // teal-500
  '#A855F7', // purple-500
  '#EAB308', // yellow-500
  '#22C55E', // green-500
  '#F43F5E', // rose-500
  '#0EA5E9', // sky-500
  '#6B7280', // gray-500
  '#374151', // gray-700
  '#1F2937', // gray-800
  '#111827', // gray-900
]; 